[package]
name = "rna_edit_distance"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = "0.8.4"
rayon = "1.5.1"
libc = "0.2.101"
rust-htslib = "*"
